# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Di's Blog
subtitle: 白天是个程序员，晚上是个有抱负的思想家
author: diwa
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://luodi.pub
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

#Custom Setting Start

# Site settings
SEOTitle: 迪娃的博客 | Di's Blog
header-img: img/home-bg.jpg
email: 543667537@qq.com
description: "欢迎！我白天是个程序员，晚上就是个有抱负的思想家，如果碰到周末，也是一个赖床爱好者。 这是我的博客。我住在天朝的魔都，有条叫做德芙的狗。"
keyword: "it 程序员 代码"


# SNS settings
# RSS: false
weibo_username:     xxxxxxxxx 
zhihu_username:     di.luo_home
github_username:    LuoDi-Nate
twitter_username:   
facebook_username:  
linkedin_username:  

# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: 
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: false # set to false if you want to use Comment without Sharing


# Analytics settings
# Baidu Analytics
ba_track_id: 
# Google Analytics
ga_track_id: ''            # Format: UA-xxxxxx-xx
ga_domain: 


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "我会变得更强, 因为我没有停下."
sidebar-avatar: /img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


# Friends
friends: [
    {
        title: "Foo",
        href: "#"
    },{
        title: "Bar",
        href: "#"
    },{
        title: "Example Friends",
        href: "#"
    },{
        title: "It helps SEO",
        href: "#"
    }
]


#Custom Setting End



# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: huxblog

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:LuoDi-Nate/LuoDi-Nate.github.io.git
  branch: master
